/*
 * opensha-dev dependencies
 */

apply plugin: 'java-library'


ext {
    parentProject = 'opensha'
}

apply from: '../opensha/build-common.gradle'

// buildscript {
//     repositories {
//         mavenCentral()
//         gradlePluginPortal()
//     }
//     dependencies {
//         classpath "gradle.plugin.com.github.johnrengelman:shadow:7.1.2"
//     }
// }

// apply plugin: 'application'
// apply plugin: 'com.github.johnrengelman.shadow'

// tasks.withType(AbstractArchiveTask).configureEach {
//     duplicatesStrategy = DuplicatesStrategy.EXCLUDE
// }

dependencies {

    api "ghsc:nshmp-lib:1.7.15"
    
    implementation 'org.apache.pdfbox:pdfbox:2.0.6'
    implementation 'org.apache.commons:commons-collections4:4.1'
    api 'uk.me.berndporr:iirj:1.0'
    implementation 'com.github.haifengl:smile-core:2.6.0'
    
    /* no remote repo */
    implementation files('lib/EventWebService.jar')
    api files('lib/flanagan.jar') // FFT and PSD library along with other tools

    implementation project(path: ':opensha')
    implementation project(path: ':opensha', configuration: 'implResolvable')

    implementation 'org.apache.hadoop:hadoop-common:3.5.0'
    implementation 'org.apache.hadoop:hadoop-mapreduce-client-core:3.5.0'
    implementation 'org.apache.parquet:parquet-avro:1.15.1'
    implementation 'org.apache.avro:avro:1.12.1'

    testImplementation 'junit:junit:4.12'
}

// application {
//     mainClass = 'scratch.anne.risk_system_vb.gui.PBRAppUI'
// }

// shadowJar {
//     archiveBaseName.set("PBRcalculator")
//     archiveClassifier.set("")
//     archiveVersion.set("")

//     manifest {
//         attributes(
//             'Main-Class': application.mainClass
//         )
//     }
// }
